### ISSUE TITLE
DFSFileExplorer.explore

### ISSUE THREAD

**Issue by Ga-3tan** [MazieroMarco/https-github.com-SoftEng-HEIGVD-Teaching-HEIGVD-RES-2021-Labo-Java-IO#6]
Implements explore method

This implementation of the IFileExplorer interface performs a depth-first exploration of the file system and invokes the visitor for every encountered node (file and directory). When the explorer reaches a directory, it visits all files in the directory and then moves into the subdirectories.

**Comment by MazieroMarco** [comment]
Working on it.
