### ISSUE TITLE
FileNumberingFilterWriter

### ISSUE THREAD

**Issue by Ga-3tan** [MazieroMarco/https-github.com-SoftEng-HEIGVD-Teaching-HEIGVD-RES-2021-Labo-Java-IO#7]
This class transforms the streams of character sent to the decorated writer. When filter encounters a line separator, it sends it to the decorated writer. It then sends the line number and a tab character, before resuming the write process.

Hello\n\World -> 1\Hello\n2\tWorld

**Comment by MazieroMarco** [comment]
Working on it !

**Comment by Ga-3tan** [comment]
ok good
